### ISSUE TITLE
compilation on jessie

### ISSUE THREAD

**Issue by davelawr** [patrikolausson/dispmanx_vnc#14]
Hi,
I'm trying to compile on rpi/wheezy with gcc version 4.9.2 (Raspbian 4.9.2-10)  and I'm getting this error:

```
Logger.hpp: In destructor ‘Logger::~Logger()’:
Logger.hpp:33:16: error: ‘put_time’ is not a member of ‘std’
   std::cerr << std::put_time(&bt, "%F %X") << "." << std::setfill('0') << std::setw(3) << ms.count() << std::setw(0)
                ^

```
Using 4.8 (as per your instructions!) I get different problems:

```

# make CXX=g++-4.8
g++-4.8 -Wall -std=c++11 -O3 -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -c DMXVNCServer.cpp -o DMXVNCServer.o
In file included from /usr/include/rfb/rfb.h:44:0,
                 from DMXVNCServer.hpp:11,
                 from DMXVNCServer.cpp:1:
/usr/include/c++/4.8/bits/sstream.tcc: In member function ‘virtual std::basic_stringbuf<_CharT, _Traits, _Alloc>::int_type std::basic_stringbuf<_CharT, _Traits, _Alloc>::overflow(std::basic_stringbuf<_CharT, _Traits, _Alloc>::int_type)’:
/usr/include/c++/4.8/bits/sstream.tcc:110:39: error: expected unqualified-id before ‘(’ token
    const __size_type __opt_len = std::max(__size_type(2 * __capacity),
                                       ^
In file included from DMXVNCServer.cpp:4:0:
Logger.hpp: In destructor ‘Logger::~Logger()’:
Logger.hpp:33:16: error: ‘put_time’ is not a member of ‘std’
   std::cerr << std::put_time(&bt, "%F %X") << "." << std::setfill('0') << std::setw(3) << ms.count() << std::setw(0)
                ^
In file included from /usr/include/rfb/rfb.h:44:0,
                 from DMXVNCServer.hpp:11,
                 from DMXVNCServer.cpp:1:
DMXVNCServer.cpp: In member function ‘void DMXVNCServer::Run(int, const string&, int, bool, bool, bool, bool, bool, bool, const string&)’:
DMXVNCServer.cpp:243:17: error: expected unqualified-id before ‘(’ token
            std::max(m_frameRect.left / 2, x * m_imageMap.pixelsPerRegion / 2),
                 ^
DMXVNCServer.cpp:244:17: error: expected unqualified-id before ‘(’ token
            std::max(m_frameRect.top / 2, y * m_imageMap.pixelsPerRegion / 2),
                 ^
DMXVNCServer.cpp:250:17: error: expected unqualified-id before ‘(’ token
            std::max(m_frameRect.left, x * m_imageMap.pixelsPerRegion),
                 ^
DMXVNCServer.cpp:251:17: error: expected unqualified-id before ‘(’ token
            std::max(m_frameRect.top, y * m_imageMap.pixelsPerRegion),
                 ^
DMXVNCServer.cpp:271:35: error: expected unqualified-id before ‘(’ token
       auto idleSleepFactor = std::max(std::chrono::seconds{1}.count(), std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - m_timeLastFrameChange).count());
                                   ^
DMXVNCServer.cpp:300:21: error: expected unqualified-id before ‘(’ token
    sleep_for = std::max(timeToTakePicture, std::chrono::steady_clock::duration{std::chrono::milliseconds{m_server->deferUpdateTime}});
                     ^
DMXVNCServer.cpp: In member function ‘std::chrono::_V2::steady_clock::duration DMXVNCServer::TimeToTakePicture()’:
DMXVNCServer.cpp:322:14: error: expected unqualified-id before ‘(’ token
  return std::max(std::chrono::steady_clock::duration{}, m_pictureTimeout - elapsed);
              ^
DMXVNCServer.cpp:323:1: warning: control reaches end of non-void function [-Wreturn-type]
 };
 ^
Makefile:29: recipe for target 'DMXVNCServer.o' failed
make: *** [DMXVNCServer.o] Error 1

```
(I must have had this working before as I sent you a note in Jan 2017 about inverted Y axis)

**Comment by patrikolausson** [comment]
Please try the latest version.

**Comment by davelawr** [comment]
Hi,
Sorry, only just have a chance to test this:
working on raspbian jessie and stretch.
I had to install libegl1-mesa-dev and libgles2-mesa-dev
Y-axis correct for both orientations of touch screen.
